auth:
  rootPassword: "devops-test"
primary:
  tolerations:
  - key: "system"
    operator: "Exists"
    effect: "NoSchedule"
secondary:
  tolerations:
  - key: "system"
    operator: "Exists"
    effect: "NoSchedule"
